export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          service_type: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          website_url: string | null;
          logo_url: string | null;
          voice_samples: Json;
          voice_tone: string;
          brand_keywords: string[] | null;
          avoid_keywords: string[] | null;
          blooio_number: string | null;
          resend_domain: string | null;
          gbp_account_id: string | null;
          gbp_location_id: string | null;
          gbp_access_token: string | null;
          gbp_refresh_token: string | null;
          wp_site_url: string | null;
          wp_username: string | null;
          wp_app_password: string | null;
          review_request_delay_hours: number;
          review_request_method: string;
          auto_respond_reviews: boolean;
          auto_post_gbp: boolean;
          auto_post_blog: boolean;
          referral_reward_type: string;
          referral_reward_value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          service_type: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          website_url?: string | null;
          logo_url?: string | null;
          voice_samples?: Json;
          voice_tone?: string;
          brand_keywords?: string[] | null;
          avoid_keywords?: string[] | null;
          blooio_number?: string | null;
          resend_domain?: string | null;
          gbp_account_id?: string | null;
          gbp_location_id?: string | null;
          gbp_access_token?: string | null;
          gbp_refresh_token?: string | null;
          wp_site_url?: string | null;
          wp_username?: string | null;
          wp_app_password?: string | null;
          review_request_delay_hours?: number;
          review_request_method?: string;
          auto_respond_reviews?: boolean;
          auto_post_gbp?: boolean;
          auto_post_blog?: boolean;
          referral_reward_type?: string;
          referral_reward_value?: number;
        };
        Update: Partial<Database["public"]["Tables"]["businesses"]["Insert"]>;
      };
      users: {
        Row: {
          id: string;
          business_id: string;
          full_name: string;
          email: string;
          role: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          business_id: string;
          full_name: string;
          email: string;
          role?: string;
          avatar_url?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };
      jobs: {
        Row: {
          id: string;
          business_id: string;
          created_by: string | null;
          title: string | null;
          service_type: string | null;
          customer_name: string | null;
          customer_email: string | null;
          customer_phone: string | null;
          address: string;
          city: string | null;
          state: string | null;
          zip: string | null;
          lat: number | null;
          lng: number | null;
          raw_notes: string | null;
          ai_story: string | null;
          ai_story_approved: boolean;
          status: string;
          completed_at: string | null;
          review_requested: boolean;
          review_request_sent_at: string | null;
          gbp_posted: boolean;
          gbp_post_id: string | null;
          blog_posted: boolean;
          blog_post_url: string | null;
          social_posted: Json;
          neighborhood_campaign_sent: boolean;
          mailer_sent: boolean;
          mailer_tracking_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          created_by?: string | null;
          title?: string | null;
          service_type?: string | null;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          address: string;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          lat?: number | null;
          lng?: number | null;
          raw_notes?: string | null;
          ai_story?: string | null;
          ai_story_approved?: boolean;
          status?: string;
        };
        Update: Partial<Database["public"]["Tables"]["jobs"]["Insert"]>;
      };
      job_photos: {
        Row: {
          id: string;
          job_id: string;
          business_id: string;
          storage_path: string;
          photo_url: string;
          photo_type: string;
          sort_order: number;
          original_lat: number | null;
          original_lng: number | null;
          geo_tagged: boolean;
          exif_data: Json | null;
          caption: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          business_id: string;
          storage_path: string;
          photo_url: string;
          photo_type?: string;
          sort_order?: number;
          original_lat?: number | null;
          original_lng?: number | null;
          geo_tagged?: boolean;
          exif_data?: Json | null;
          caption?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["job_photos"]["Insert"]>;
      };
    };
  };
}
